name: Compile NeoForge Kits for Snapshot
description: Compile and Publish (Locally) NeoForge Kits for MC Snapshots
inputs:
  mc-version:
    description: 'The snapshot version to compile'
    default: ''
    required: false
  java-version:
    description: 'The JDK version to use (default: 17)'
    default: '17'
    required: false
  java-distro:
    description: 'Which JDK distribution to use (default: github)'
    default: 'github'
    required: false
  skip-gradle-setup:
    description: 'Skip gradle setup, set to "true"'
    default: 'false'
    required: false

runs:
  using: composite
  steps:
    - name: Clone NeoForge Kits
      shell: bash
      run: |
        git clone -q -b port/${{ inputs.mc-version }} --depth 1 https://github.com/neoforged/NeoForge Kits

    - uses: null2264/actions/gradle-setup@master
      if: ${{ inputs.mc-version != '' && inputs.skip-gradle-setup != 'true' }}
      with:
        java: ${{ inputs.java-version }}
        distro: ${{ inputs.java-distro }}
        working-directory: "Kits"

    - name: Making sure Gradle Wrapper is executable
      if: ${{ inputs.mc-version != '' && inputs.skip-gradle-setup == 'true' }}
      working-directory: "Kits"
      shell: bash
      run: chmod +x ./gradlew

    - name: Compile and Publish
      working-directory: 'Kits'
      shell: bash
      run: |
        echo "org.gradle.daemon=false" >> gradle.properties
        ./gradlew neoforge:setup
        ./gradlew neoforge:publishToMavenLocal
