name: Compile MC Mod with Preprocessor
description: Compile MC Mod that using ReplayMod's Preprocessor
inputs:
  versions:
    description: 'List of versions that needed to be compiled, separated by space'
    required: true
  daemon:
    description: 'Whether to enable gradle daemon or not, ("y" to enable, "n" to disable)'
    default: 'y'
    required: false

runs:
  using: composite
  steps:
    - name: Setup Gradle for ReplayMod's Preprocessor
      shell: bash
      run: |
        echo "org.gradle.java.installations.fromEnv=JAVA_HOME,JAVA_HOME_8_X64,JAVA_HOME_17_X64,JAVA_HOME_21_X64" >> gradle.properties
        echo "org.gradle.jvmargs=-Xmx6G" >> gradle.properties
        echo "org.gradle.cache.cleanup=false" >> gradle.properties

    - name: Disable Gradle Daemon
      run: |
        daemon=${{ inputs.daemon == 'y' && 'true' || 'false' }}
        echo "org.gradle.daemon=$daemon" >> gradle.properties

    - name: Build with Gradle
      shell: bash
      run: |
        MOD_VERSIONS=(${{ inputs.versions }})

        for i in "${MOD_VERSIONS[@]}"; do
                echo "Compiling ${i}"
                ./gradlew :${i}:build --stacktrace
        done
