name: Gradle Setup
description: Set up the basics to run gradle
inputs:
  java:
    description: 'The JDK version to use (default: 17)'
    default: '17'
    required: false
  distro:
    description: 'Which JDK distribution to use (default: github)'
    default: 'github'
    required: false
  working-directory:
    description: 'Set working directory to use (default: .)'
    default: '.'
    required: false
  gradle-home-cache-includes:
    description: 'List of folder/file that should be cached'
    default: |
      caches
      notifications
    required: false
  gradle-home-cache-excludes:
    description: 'List of folder/file that should NOT be cached'
    default: ''
    required: false
  gradle-cache-if:
    description: 'Whether or not gradle should be cached'
    default: ${{ github.event.repository != null && github.ref_name != github.event.repository.default_branch }}
    required: false

runs:
  using: composite
  steps:
    - name: Setup JDK ${{ inputs.java }} (Custom Distro)
      uses: actions/setup-java@v3
      if: ${{ inputs.distro != 'github' }}
      with:
        distribution: ${{ inputs.distro }}
        java-version: ${{ inputs.java }}

    - name: Setup JDK ${{ inputs.java }} (GitHub)
      # https://github.com/actions/runner-images/blob/07d23cf/images/ubuntu/Ubuntu2204-Readme.md#java
      if: ${{ inputs.distro == 'github' }}
      shell: bash
      run: |
        echo "JAVA_HOME=$(echo $JAVA_HOME_${{ inputs.java }}_X64)" >> "$GITHUB_ENV"

    - name: Setup Gradle
      if: ${{ inputs.working-directory == '.' }}
      uses: gradle/actions/setup-gradle@v3
      with:
        validate-wrappers: true
        gradle-home-cache-includes: ${{ inputs.gradle-home-cache-includes }}
        gradle-home-cache-excludes: ${{ inputs.gradle-home-cache-excludes }}
        cache-read-only: ${{ input.gradle-cache-if }}

    - name: Making sure Gradle Wrapper is executable
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: chmod +x ./gradlew
